project:
  type: book

book:
  title: "ComputationalSystemsBiology"
  author: "Karthik Dani"
  date: "4/20/2024"
  chapters:
    - index.qmd
    - introduction.qmd
    - fundamentals_of_math_modeling.qmd
    - network_biology.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

